INSERT INTO
  jawaban_quiz (soal_quiz_id, text_jawaban, benar)
VALUES
  (1,'print',true),
  (1,'output',false),
  (2,'print"GUGUM"',false),
  (2,'print("GUGUM")',true),
  (2,'print(GUGUM)',false),
  (3,'Bahasa Pemroraman',true),
  (3,'Alat pembuatan web',false),
  (3,'Aplikasi edit video',false),
  (4,'TIDAK',false),
  (4,'YA',true),
  (5,'6.0',false),
  (5,'-6',false),
  (5,'6',true),
  (6,'6.0',true),
  (6,'6',false),
  (6,'8',false),
  (7,'7.0',true),
  (7,'7',false),
  (7,'2/4',false),
  (8,'15',false),
  (8,'15.0',true),
  (8,'1.5',false),
  (9,'**',true),
  (9,'^^',false),
  (9,'^',false),
  (10,'8.0',true),
  (10,'0.8',false),
  (10,'8.08',false),
  (11,'2',true),
  (11,'0',false),
  (11,'3',false),
  (12,'1',true),
  (12,'7',false),
  (12,'0',false);
