export const CREATE_BAB = "CREATE_BAB"
export const RETRIEVE_BAB = "RETRIEVE_BAB"
export const UPDATE_BAB = "UPDATE_BAB"
export const DELETE_BAB = "DELETE_BAB"
export const LOADING_BAB = "LOADING_BAB"